### PR TITLE
Fix month display and add perform optimizations

### PR DESCRIPTION
**Pull request by rodolfobarretoweb**

### CODE REVIEW

**Comment by christopherdro** [comment]
Thanks for the PR.

Looks like your reverting something a merged a few weeks ago.

Did I miss something?

**Comment by rodolfobarretoweb** [comment]
No, I maked this modification in another branch, so I deleted.

**Comment by christopherdro** [comment]
@simonmarton This is reverting your change from your last commit.

https://github.com/christopherdro/react-native-calendar/commit/aeb299e32c796e589ff97c1e598dfa1d045d2f5d



@rodolfobarretoweb I'm also unclear how this PR adds performance optimizations?

**Comment by rodolfobarretoweb** [comment]
@christopherdro there is some lag when I push the controls buttons, so I put some optimizations to get a better performance. One example is do not create a variable in loops commands. When I push this buttons with this optimization I receive a better response.

Sorry my english, this is not more native language

**Pull request closed without merging**
