### PR TITLE
Fix custom weekendDayButton not working #136

### PR DESCRIPTION
**Pull request by CreamTreacle**
Fix custom weekendDayButton not working #136

### CODE REVIEW

**Comment by deejaygeroso** [comment]
Any update on this??

**Comment by shinnc** [comment]
@christopherdro any update on this and a new release?

**Comment by gomdolkim** [comment]
@christopherdro Do you have plan for new release? :)

**Comment by christopherdro** [comment]
Thanks!

Sorry for the delay.

**Pull request merged**
