### PR TITLE
[ADDED] orientation change support

### PR DESCRIPTION
**Pull request by EddMoo**
Wrapped the Touchable's with Views on Day.js so instead of using DEVICE_WIDTH/7 you can use flex, that and some changes con styles so the Touchable's use all width, as before.

### CODE REVIEW

**Comment by christopherdro** [comment]
Thanks for submitting the PR. The codebase uses 2 space indentation.
Could you update the code in your PR?

**Comment by EddMoo** [comment]
Sure!

**Comment by christopherdro** [comment]
Thanks for the PR and fixes.

When I run your code changes with the example app I get this.

simulator screen shot dec 25 2016 9 40 42 pm

**Comment by hejiaji** [comment]
@EddMoo Any update?

**Pull request closed without merging**
