### PR TITLE
Resolve merge conflicts for #105 #106 and fix resulting display issue

### PR DESCRIPTION
**Pull request by lukescott**
Merges #105 and #106 and fixes display issue seen after combining the two features.

### CODE REVIEW

**Comment by christopherdro** [comment]
@lukescott LGTM. Could you update the README to reflect your changes before we merge this in?

**Comment by christopherdro** [comment]
@lukescott Also appears to have some small merge conflicts. Would you mind trying to resolve those?

**Comment by coderdave** [comment]
Where are we at in resolving these conflicts? If we can't resolve them, maybe we can at least merge in #106? That one looks like it will at least allow us to use the calendar in landscape mode?

**Comment by edwardlafoy** [comment]
Any idea of when we could get this merged in?

**Comment by willedanielsson** [comment]
Will this or atleast #106 be merged since its a quite serious "bug"? Great component though!

**Comment by coderdave** [comment]
For anyone watching this thread, I went ahead and resolved the conflicts on https://github.com/christopherdro/react-native-calendar/pull/106 in the `webconnex-container-width` branch.

I opted to resolve https://github.com/christopherdro/react-native-calendar/pull/106 instead of this one since it already had a ton of conflicts as it was, so I can't imagine how much more it would be with this one.

**Pull request closed without merging**
