### PR TITLE
Added possibility to style day when there is an event

### PR DESCRIPTION
**Pull request by KGALLET**
Hi, 

Here is an other way to show event at the selected dates instead of using the indicator below the date.

Don't forget to put the following customStyle in the Calendar customStyle props : 

```
  const customStyle = {
      selectedDayCircle: { backgroundColor: 'transparent' },
      selectedDayText: { color: 'black' },
      eventIndicator: { backgroundColor: 'transparent' },
      eventIndicatorFiller: { height: 0, width: 0, marginTop: 0, borderRadius: 0 },
      hasEventCircle: { backgroundColor: 'orange' },
      hasEventText: { color: 'white' }
    }
```

Thank's :)

### CODE REVIEW

**Comment by christopherdro** [comment]
Thanks for the PR! Could you add this to the Custom Styles section in the README as well?

**Comment by KGALLET** [comment]
It's ok for you or I need to give more details ?

**Comment by christopherdro** [comment]
You can remove the note about this PR and just leave in `hasEventCircle` and `hasEventText`.

Thanks!

**Comment by KGALLET** [comment]
Done 👍

**Pull request merged**
