### PR TITLE
Add contentWidth prop

### PR DESCRIPTION
**Pull request by cornedor**
Add's a property to the Calendar to set the content width, allowing you to put the calendar in smaller parts of your app.

### CODE REVIEW

**Comment by christopherdro** [comment]
@coderdave @tomaskulich I like the idea of this? What do you guys think?

@cornedor Any chance you have a screenshot of the calendar using the prop?

**Comment by coderdave** [comment]
I like the idea of it also.

**Comment by tomaskulich** [comment]
Sounds great. However, please don't implement new features until we merge https://github.com/christopherdro/react-native-calendar/pull/21 (It'll be ready on 23.5.), because it will be hell to merge :)

**Comment by christopherdro** [comment]
Sounds good.

**Comment by cornedor** [comment]
I've switched to a date/time picker in the project where I made those changes for. But i might reimplement my changes after #21 is merged if necessary, i'll probably have to make a new merge request looking at the amount of changes @tomaskulich made :-)

**Comment by choru-k** [comment]
I think this idea is good.
why this PR is not merged?

**Comment by tomaskulich** [comment]
@christopherdro: LGTM, is there anything that prevents merging?

**Comment by christopherdro** [comment]
Merge conflicts with the recent changes.

**Comment by tomaskulich** [comment]
Oh, my bad :) I deleted the comment.

**Comment by Andreyco** [comment]
I think this is essentially solve by this [commit](https://github.com/christopherdro/react-native-calendar/commit/cc5dc17b49385503891b1d66dc595109718a4898).
You were able to set style for component & month container. Unfortunately, style for month container was not taken into account... Commit fixes this issue. Could you please try out for you use case? I was able to shrink whole component to occupy less then screen width.

**Pull request closed without merging**
