### PR TITLE
add hasEvent to customize hasEvent

### PR DESCRIPTION
**Pull request by evollu**
My app has recursive events so I can't pass an array into calendar. 
add hasEvent callback to allow more custom logics

### CODE REVIEW

**Comment by christopherdro** [comment]
@evollu Thank you for the PR. Please take a look at the latest changes in master since there significant amount of updates. I think what your looking for is implemented.

**Comment by evollu** [comment]
@christopherdro please check my updated pull request. Your changes still can't solve my problem.

**Comment by christopherdro** [comment]
@evollu Thanks for updating the PR. I guess I'm still a bit confused that what you are trying to do here. What do you mean exactly that your app has recursive events. Isn't there a way you can check the selected date against your own records? Or keep track of your recursive events?

Just seems a bit redundant.

**Comment by evollu** [comment]
For example, I have an event happens every Monday. In the existing code, I have no way to build eventDate array as it is infinite

**Comment by tomaskulich** [comment]
@evollu I believe, you mean recurring (not recursive) events? Which does not fit to the fix-sized array?

did you consider to simply calculate a 'long enough' array of event dates and use that? If you want to display events for one year, that's just 365 events, which is quite small array; OTOH, I cannot imagine the use-case when someone really needs their recurring events one year in the future!

Not that I don't like the change you are proposing, but it complicates the API and I'm not sure if the gain is so big.

**Comment by christopherdro** [comment]
I have to agree. You can add events to the calendar based on the current date they are on as another option.

**Comment by evollu** [comment]
yeah.. recurring events. This is a workaround. I will keep it in my fork if you don't like the change.
@christopherdro do you mean subscribing on prev/next press event and update array on the fly? Can you have swipe callbacks pass `newMonth`?

**Comment by christopherdro** [comment]
@evollu Yes, the callbacks pass you back the current month.

**Comment by evollu** [comment]
I see in code it is `this.props.onSwipePrev()` so newMonth is not passed into callback. Can you change that?
Also I'm curious what is the use case to separate click vs. swipe callbacks

**Comment by christopherdro** [comment]
Your right, the date is missing from the `onSwipeNext` and `onSwipePrev` but exists on the touch callbacks. Use case for using touch is if user disables the scroll feature.

**Comment by evollu** [comment]
I mean can both button and swipe fire the same event?

**Comment by christopherdro** [comment]
Each triggers its respective prop on the 'Calendar' component. No need to change the API.

**Comment by christopherdro** [comment]
just added the callbacks via cd46101a492693600b8c00c8c044b362d866146e
you can give that a shot if you'd like

**Comment by evollu** [comment]
ok thanks

**Pull request closed without merging**
