### PR TITLE
Fix exceptions in React 16 for React.PropTypes being deprecated

### PR DESCRIPTION
**Pull request by brianyamasaki**
React 16 deprecates React.PropTypes in favor of a separate library 'prop-types'.

Trivial change, simply import PropTypes from 'prop-types instead of from React.

### CODE REVIEW

**Comment by stianjensen** [comment]
should prop-types also be added as a dependency in package.json?

**Comment by brianyamasaki** [comment]
I did not have to do that for any projects. I am guessing prop-types are a
required package for React 16. I have the same sources building with React
15 with no problems.

**Comment by stianjensen** [comment]
Then I guess no change in yarn.lock should be needed.

**Comment by hwaterke** [comment]
Could this be merged?

**Comment by stianjensen** [comment]
I hope so! Let me know if you want me to make a new pull request for this.

**Comment by coderdave** [comment]
I already merged in https://github.com/christopherdro/react-native-calendar/pull/106 that had this fixed already.

**Pull request closed without merging**
